languageCode = "en-gb"
title = "Luc Engelen"
baseUrl = "https://ljpengelen.github.io/"
theme = "februari-2017"

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  author = "Luc Engelen"
  googleAnalyticsProperty = "UA-324041-10"
